[package]
name = "musicglass-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
musicglass-core = { path = "../core" }
musicglass-metadata = { path = "../metadata" }
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[dev-dependencies]
musicglass-task-manager = { path = "../task-manager" }
